spring:
  application:
    name: autoFidle
  profiles:
    active: dev
  quartz:
    jdbc:
      initialize-schema: always
    job-store-type: jdbc
    properties:
      org:
        quartz:
          jobStore:
            acquireTriggersWithinLock: true
            class: org.quartz.impl.jdbcjobstore.JobStoreTX
            clusterCheckinInterval: 10000
            driverDelegateClass: org.quartz.impl.jdbcjobstore.StdJDBCDelegate
            isClustered: true
            tablePrefix: qrtz_
            useProperties: false
          scheduler:
            instanceId: AUTO
            instanceName: clusteredScheduler
            instanceIdGenerator:
              class: org.quartz.simpl.HostnameInstanceIdGenerator
          threadPool:
            class: org.quartz.simpl.SimpleThreadPool
            threadCount: 15
            threadPriority: 5
            threadsInheritContextClassLoaderOfInitializingThread: true
#server
server:
  port: 8086
  servlet:
    context-path: /
