#server
server:
  port: 8089
  servlet:
    context-path: /
  max-http-header-size: 8192
spring:
  redis:
    database: 1
    host: 127.0.0.1
    password: 123456
    port: 6379
  klock:
    address: 127.0.0.1:6379
    database: 2
    password: 123456
    waitTime: 60 #获取锁最长阻塞时间（单位：秒）
    lease-time: 60 #已获取锁后自动释放时间（单位：秒）
dubbo:
  registry:
    address: zookeeper://127.0.0.1:2181
  protocol:
    port: -1
    name: dubbo
  provider:
    filter: logFilter
    retries: -1
    timeout: 5000
  consumer:
    filter: logFilter
    retries: -1
    timeout: 5000
  scan:
    base-packages: com.zht.dubbo #dubbo 扫描包