#server
server:
  port: 8086
  servlet:
    context-path: /
#spring-boot
spring:
  application:
    name: springBootShiro
  profiles:
    active: dev
  freemarker:
    cache: false
    charset: utf-8
    prefer-file-system-access: false
    settings:
      number_format: 0
    suffix: .ftl
  http:
    encoding:
      charset: utf-8
      enabled: true
      force: true
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  mvc:
    view:
      prefix: /templates
      suffix: .html
  servlet:
    multipart:
      max-request-size: 500MB
      max-file-size: 50MB