#spring-boot
spring:
  application:
    name: springBoot_fastdfs
  profiles:
    active: dev
  aop:
    proxy-target-class: true
    auto: true
  mvc:
    view:
      prefix: /templates/
      suffix: .html
  freemarker:
    cache: false
    charset: utf-8
    prefer-file-system-access: false
    settings:
      number_format: 0
  http:
    encoding:
      charset: utf-8
      enabled: true
      force: true
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  devtools:
    restart:
      enabled: true
  servlet:
    multipart:
      max-request-size: 500MB
      max-file-size: 50MB
#logging
logging:
  config: classpath:logback-spring.xml
# ===================================================================
# 分布式文件系统FDFS配置
# ===================================================================
fdfs:
  so-timeout: 1501
  connect-timeout: 601
  thumb-image:             #缩略图生成参数
    width: 150
    height: 150
  tracker-list:            #TrackerList参数,支持多个
    - 192.168.0.103:22122
  pool:
    #从池中借出的对象的最大数目（配置为-1表示不限制）
    max-total: -1
    #获取连接时的最大等待毫秒数(默认配置为5秒)
    max-wait-millis: 5000
    #每个key最大连接数
    max-total-per-key: 50
    #每个key对应的连接池最大空闲连接数
    max-idle-per-key: 10
    #每个key对应的连接池最小空闲连接数
    max_idle_per_key: 5