server:
  port: 8089
  servlet:
    context-path: /
    session: # spring session 超时时间
      timeout: 30m
spring:
  application:
    name: gulimall-product
  thymeleaf:
    cache: false
  redis:
    password: 123456
    database: 8
  session:  # spring session 使用redis
    store-type: redis
  devtools:
    restart:
      enabled: false
  rabbitmq:
    publisher-confirms: true
    publisher-returns: true
    template:
      mandatory: true
    listener:
      direct:
        acknowledge-mode: manual